#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Mapping AirTable Tables to CRM
#+date: <2021-07-04 Sun>
#+author: Clifford Wulfman
#+email: cwulfman@princeton.edu
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.4.4)

There are, at the outset, two tables in the BDDA's AirTable base.
They contain data compiled by the BDDA team, and the records (rows)
are not aligned with CRM entities or properties.

One of the first data tasks is to align this data with CRM entities
and properties in a new set of tables.

* Places Table Data Dictionary
  The records in this table constitute a gazetteer for the accounts of
  plague-related events.  The toponyms (E44 Place Appellations) are
  linked to E53 Places; the CRM places are the entities with
  geospatial coordinates.

** table
| BDDA                | CRM                      | belongs with Place |
|---------------------+--------------------------+--------------------|
| Title               | E41 Appellation          |                    |
| Variants            | E41 Appellation, SKOS    |                    |
| Aat_types           | P2 has_type              | yes                |
| Title_source        | P67 is referred to by    |                    |
| End                 |                          |                    |
| Ccodes              | P89 falls within         | yes                |
| Parent_name         | P89 falls within         | yes                |
| Latitude, Longitude | P168 place is defined by | yes                |


** Title
   #+begin_quote
   The name of the place mentioned in the document, as it is mentioned in the document.
   #+end_quote

   - E48 Place Name ::
     http://www.cidoc-crm.org/html/5.0.4/cidoc-crm.html#E48
     The ususal entry in place-name gazetteers.

   - E44 Place Appellation ::
     http://www.cidoc-crm.org/html/5.0.4/cidoc-crm.html#E44
     A more general form of place name; it also subsumes E47 Spatial Coordinates.

** Variants
   #+begin_quote
   Includes variants of the name of the place mentioned in the title
   field including modern variants and variants in several languages.
   #+end_quote

   These are either distinct _E48 Place Names_, or they are spelling
   variants.  If the latter, they should be modeled with SKOS.

** Aat_types
   #+begin_quote
   The Getty Art and Architecture Thesaurus
   (https://www.getty.edu/research/tools/vocabularies/aat/help.html)
   This table uses the hierarchy list from Linked Pasts:
   https://github.com/LinkedPasts/linked-places/blob/master/tsv_0.2.md
   #+end_quote

   Not a property of the name, but of the _E53 Place_ to which it refers
   - _P2 has type_ _E55 Type_
     #+begin_src n3
	bdda:placexx :P2_has_type <URI of AAT type>
     #+end_src

** Title_source
   #+begin_quote
   Secondary source reference about the place mentioned in the title
   field.
   #+end_quote

   _P67 is referred to by_ used in OpenAtlas to link to documents
   mentioning a place or an event.

** End
   #+begin_quote
   Latest year of the reference in the document to the place mentioned
   in the title field.
   #+end_quote

   Don't know yet!

** Ccodes
   #+begin_quote
   Country codes as per the ISO-3166 standard that uses the two-letter
   country codes. The code refers to the modern country where the
   place mentioned in the title field is in.
   #+end_quote

   Not a property of the name, but of the place to which the name refers.

   _P89 falls within_ E53 Place; the place has an identifier


** Parent_name
   #+begin_quote
   A single toponym containing the place mentioned in the title
   field. Derived from Linked Places optional fields’ list:
   https://github.com/LinkedPasts/linked-places/blob/master/tsv_0.2.mda
   #+end_quote

   _P89 falls within_

** References
   #+begin_quote
   Refers to the unique ID field (number) in the Turkish Archives table
   #+end_quote

** Latitude
   Not a property of the name, but of the E53 Place to which it refers.

** Longitude
   Not a property of the name, but of the E53 Place to which it refers.

* TurkishArchives Data Dictionary

** id
** place name
   #+begin_quote
   place mentioned in the archival document from the collection
   mentioned in column E (the COLLECTION field)
   #+end_quote

   Equivalent to the Title field in the Places table

** PossibleOtherPlaces
   #+begin_quote
   ignore
   #+end_quote
** title (from Places)
   #+begin_quote
   links to places table
   #+end_quote

   No longer needed in the LOD model

** COLLECTION
   #+begin_quote
   archival collection where the place is mentioned
   #+end_quote

   This field, and the FOLDER/DOC field, are bibliographic/archival
   data.  It is not yet clear how we want or need to model source
   documents and archives
** FOLDER/DOC
   #+begin_quote
   Folder/Doc in the collection
   #+end_quote

   See COLLECTION

** Date_Modern (YYYY-MM-DD) and Date_Document
   The same _E52 Time-Span_ incorporates both of these fields; the
   Time-Span can be _P78 is identified by_ more than one _E49 Time
   Appellation_ to express both the modern and original expressions of
   the date.

** SUBJECT
** EXISTENCE
** PRECAUTIONS
** DEATH NUMBER
** SUMMARY

** NUMBER OF IMAGES
** DROPBOX LINK
** FULL TEXT
** NOTES
* Examples
** Turkish Archives
*** item #96
    - id :: 96
    - Place Name :: Eşkel-i Kebir
    - Variants :: Essence
    - AAT_Types :: Neighborhood
    - Title_Source :: https://tr.wikipedia.org/wiki/Esence,_Mudanya
    - CCodes :: TR
    - Parent_Name :: Bursa
    - References :: 
